<?php $metaTitle='Admissions | Apply Online, Download Forms & Pay Fee | SGoI Kanpur'; include 'includes/header.php'; ?>
<section class="page-hero" style="--hero-img:url('<?= img_src('assets/img/page_head/adminission_Process_college.jpg') ?>')"><div class="container"><span class="breadcrumb-soft">Admissions</span><h1 class="mt-3">Admission Details, Process & Downloads</h1><p class="col-lg-8">Find course-wise admission details, online application, fee payment support, downloadable brochures and required documents.</p></div></section>
<section class="section">
  <div class="container"><div class="row g-4"><div class="col-lg-8">
    <div class="split-box mb-4" id="pay-fee"><span class="badge-soft">Pay Fee Online</span><h2 class="mt-3">Pay Your Fee Online</h2><p class="muted">Students can use the online payment facility after confirming details with the admission/accounts team. Add your live payment gateway/payment link here from admin panel or config once available.</p><a href="contact.php#admission" class="btn btn-primary">Contact Admission Department</a></div>
    <div class="split-box mb-4" id="details"><span class="badge-soft">Admission Details</span><h2 class="mt-3">Admission Details - All Departments</h2><div class="row g-3 mt-2"><?php foreach($departments as $slug=>$d): ?><div class="col-md-6"><div class="feature-card"><i class="fa-solid <?= h($d['icon']) ?>"></i><h4 class="h5"><?= h($d['name']) ?></h4><p class="muted"><?= h($d['eligibility']) ?></p><a href="department.php?slug=<?= h($slug) ?>" class="btn btn-outline-dark w-100">View Department</a></div></div><?php endforeach; ?></div></div>
    <div class="split-box mb-4" id="process"><span class="badge-soft">Process</span><h2 class="mt-3">Admission Process</h2><div class="timeline mt-3"><div class="timeline-step"><b>Step 1: Choose Department / Course</b><p class="muted mb-0">Select Pharmacy, Nursing, B.Ed. or ITI based on eligibility and career goals.</p></div><div class="timeline-step"><b>Step 2: Submit Inquiry</b><p class="muted mb-0">Fill the form with name, mobile, city, class percentage, stream and course interest.</p></div><div class="timeline-step"><b>Step 3: Counselling & Documents</b><p class="muted mb-0">Admission team explains eligibility, documents, seats, scholarship inquiry and process.</p></div><div class="timeline-step"><b>Step 4: Application & Confirmation</b><p class="muted mb-0">Complete application, registration/payment and final admission formalities.</p></div></div></div>
    <div class="split-box" id="downloads"><span class="badge-soft">Download</span><h2 class="mt-3">Brochures, Forms & Documents</h2><p class="muted">These files can be updated later from the admin/content system or server downloads folder.</p><?php foreach(get_site_downloads() as $dl): ?><div class="download-row"><div><b><?= h($dl['title']) ?></b><div class="type"><?= h($dl['type']) ?></div></div><a class="btn btn-outline-dark" href="<?= h($dl['file']) ?>" target="_blank"><i class="fa-solid fa-download me-1"></i>Download</a></div><?php endforeach; ?></div>
  </div><div class="col-lg-4" id="online-application"><div class="form-shell sticky-top" style="top:110px"><h3 class="h4">Online Application</h3><p class="muted small">Submit admission inquiry. Our team will call you for the next step.</p><?= renderLeadForm('Admissions Page') ?></div></div></div></div>
</section>
<?php include 'includes/footer.php'; ?>
