<?php
require_once 'includes/functions.php';
$slug=$_GET['slug'] ?? 'b-pharm';
if(!isset($courses[$slug])){ http_response_code(404); $slug='b-pharm'; }
$c=$courses[$slug];
$metaTitle=$c['title'].' Admission | Sakshi Group of Institutions Kanpur';
$metaDescription=$c['summary'];
include 'includes/header.php';
?>
<section class="page-hero" style="--hero-img:url('<?= img_src($c['image']) ?>')"><div class="container"><span class="breadcrumb-soft"><?= h($c['department']) ?> → <?= h($c['title']) ?></span><h1 class="mt-3"><?= h($c['title']) ?> Admission</h1><p class="col-lg-8"><?= h($c['summary']) ?></p><div class="mt-4"><a href="#enquiry" class="btn btn-gold btn-lg">Apply Now</a><a href="department.php?slug=<?= h($c['department_slug']) ?>" class="btn btn-outline-light btn-lg ms-sm-2 mt-2 mt-sm-0">View Department</a></div></div></section>
<section class="section">
  <div class="container"><div class="row g-4"><div class="col-lg-8">
    <span class="badge-soft">Course Details</span><h2 class="mt-3">About <?= h($c['title']) ?></h2><p class="muted fs-5"><?= h($c['summary']) ?></p>
    <div class="row g-3 mt-2"><div class="col-md-4"><div class="feature-card"><i class="fa-solid fa-clock"></i><h4 class="h5">Duration</h4><p class="mb-0 muted"><?= h($c['duration']) ?></p></div></div><div class="col-md-4"><div class="feature-card"><i class="fa-solid fa-list-check"></i><h4 class="h5">Eligibility</h4><p class="mb-0 muted"><?= h($c['eligibility']) ?></p></div></div><div class="col-md-4"><div class="feature-card"><i class="fa-solid fa-award"></i><h4 class="h5">Approval</h4><p class="mb-0 muted"><?= h($c['approval']) ?></p></div></div></div>
    <div class="split-box mt-4"><h2>Admission Process</h2><div class="timeline mt-3"><div class="timeline-step"><b>1. Submit Inquiry</b><p class="muted mb-0">Share name, mobile, city, class percentage, stream and course interest.</p></div><div class="timeline-step"><b>2. Eligibility Guidance</b><p class="muted mb-0">Admission team verifies course suitability and documents.</p></div><div class="timeline-step"><b>3. Application Support</b><p class="muted mb-0">Complete online/offline form and registration steps.</p></div><div class="timeline-step"><b>4. Final Admission</b><p class="muted mb-0">Complete required documents, fee process and admission formalities.</p></div></div></div>
  </div><div class="col-lg-4"><div class="form-shell sticky-top" style="top:110px"><h3 class="h4">Apply for <?= h($c['title']) ?></h3><p class="muted small">Get callback for eligibility, fees, documents and scholarship inquiry.</p><?= renderLeadForm('Course Page - '.$c['title'],$c['title']) ?></div></div></div></div>
</section>
<section class="section bg-light-subtle"><div class="container"><div class="row g-4"><div class="col-lg-6"><div class="split-box h-100"><h2>Career Opportunities</h2><ul class="mt-3"><?php foreach($c['careers'] as $x): ?><li><?= h($x) ?></li><?php endforeach; ?></ul></div></div><div class="col-lg-6"><div class="split-box h-100"><h2>Labs / Practical Training</h2><ul class="mt-3"><?php foreach($c['labs'] as $x): ?><li><?= h($x) ?></li><?php endforeach; ?></ul></div></div></div></div></section>
<section class="section"><div class="container"><div class="row g-4 align-items-center"><div class="col-lg-6"><img src="<?= img_src($c['image']) ?>" class="img-fluid rounded-premium shadow-soft" alt="<?= h($c['title']) ?>"></div><div class="col-lg-6"><span class="badge-soft">Why Choose This Course?</span><h2 class="mt-3">A course page designed like a landing page.</h2><p class="muted"><?= h($c['admission']) ?></p><div class="row g-3"><div class="col-sm-6"><div class="feature-card"><i class="fa-solid fa-user-check"></i><h5>Admission Support</h5><p class="muted mb-0">Eligibility, documents and form support.</p></div></div><div class="col-sm-6"><div class="feature-card"><i class="fa-solid fa-briefcase"></i><h5>Placement Support</h5><p class="muted mb-0">Career guidance and department-wise exposure.</p></div></div></div></div></div></div></section>
<section class="section bg-light-subtle" id="enquiry"><div class="container"><div class="form-shell"><div class="row g-4 align-items-center"><div class="col-lg-5"><h2>Request <?= h($c['title']) ?> Admission Guidance</h2><p class="muted">Our team can help you understand eligibility, documents, process and scholarship inquiry.</p></div><div class="col-lg-7"><?= renderLeadForm('Bottom Course Form - '.$c['title'],$c['title']) ?></div></div></div></div></section>
<?php include 'includes/footer.php'; ?>
