<?php $metaTitle='Pharmacy Placements | Sakshi Group of Institutions'; include 'includes/header.php'; $deptKey='pharmacy'; $deptTitle='Pharmacy Placements'; ?>
<section class="page-hero-solid" style="--hero-img:url('<?= h(img_src('assets/img/Placement-Drive-29-04-2023.jpg')) ?>')"><div class="container"><span class="page-kicker"><i class="fa-solid fa-briefcase"></i> Pharmacy Placements</span><h1>Pharmacy Placements</h1><p>Pharmacy placement support focuses on pharmacist roles, hospital pharmacy exposure, medical representative opportunities and pharma industry connects.</p></div></section>
<section class="section"><div class="container"><div class="row g-4 align-items-start"><div class="col-lg-7"><span class="badge-soft">Department Placement Cell</span><h2 class="display-serif mt-3 display-5">Career guidance for <?= h($departments[$deptKey]['name']) ?> students.</h2><p class="muted lead-lite"><?= h($departments[$deptKey]['placement']) ?></p><div class="mt-4"><?php foreach($placementCompanies[$deptKey] ?? [] as $co): ?><span class="company-pill"><i class="fa-solid fa-building"></i><?= h($co) ?></span><?php endforeach; ?></div></div><div class="col-lg-5"><div class="form-shell"><?= renderLeadForm($deptTitle) ?></div></div></div></div></section>
<section class="section bg-cream"><div class="container"><div class="section-head with-nav mb-4"><div><span class="badge-soft">Student Success</span><h2 class="display-serif mt-3 display-5">Highlights and available student images.</h2></div><div class="swiper-arrows"><button class="swiper-btn dept-place-prev"><i class="fa-solid fa-arrow-left"></i></button><button class="swiper-btn dept-place-next"><i class="fa-solid fa-arrow-right"></i></button></div></div><?php $successSlides = [];
if($deptKey==='iti') $successSlides=[['assets/img/placements/ITI/Aman_Bajpai.jpg','Aman Bajpai'],['assets/img/placements/ITI/Anup_Maurya.jpg','Anup Maurya'],['assets/img/placements/ITI/Jitendra_Sharma.jpg','Jitendra Sharma'],['assets/img/placements/ITI/Mayank_Srivastava.jpg','Mayank Srivastava']];
elseif($deptKey==='education') $successSlides=[['assets/img/placements/B-Ed/akansha-katiyar.jpg','Akansha Katiyar'],['assets/img/placements/B-Ed/ayush-vaish.jpg','Ayush Vaish'],['assets/img/placements/B-Ed/harsh-katiyar.jpg','Harsh Katiyar'],['assets/img/placements/B-Ed/Kunal.jpg','Kunal']];
elseif($deptKey==='nursing') $successSlides=[['assets/img/students/nursing-1.jpg','Nursing Student'],['assets/img/students/nursing-3.jpg','Clinical Learning'],['assets/img/hospital_visit_JL_head.jpg','Hospital Exposure'],['assets/img/gallery/nursing/IMG-20230203-WA0019.jpg','Nursing Activity']];
else $successSlides=[['assets/img/Placement-Drive-29-04-2023.jpg','Placement Drive'],['assets/img/gallery/pharmacy/IMG-20230203-WA0031.jpg','Pharmacy Activity'],['assets/img/Industrial_Visit_Head.jpg','Industrial Visit'],['assets/img/gallery/pharmacy/DSC_0242.jpg','Pharmacy Lab']]; ?>
<div class="swiper dept-placement-swiper"><div class="swiper-wrapper"><?php foreach($successSlides as $s): ?><div class="swiper-slide"><article class="placement-card-v8"><img src="<?= h(img_src($s[0])) ?>" alt="<?= h($s[1]) ?>"><div class="content"><h3><?= h($s[1]) ?></h3><p>Department-wise placement and exposure highlight.</p></div></article></div><?php endforeach; ?></div><div class="swiper-pagination dept-place-pagination"></div></div></div></section>
<?php include 'includes/footer.php'; ?>
